<?php

/**
 * Implementation of hook_menu
 */
 
 function matt_contact_menu(){
	
	//Call back
	$items['contact'] = array(
		'title' => 'Contact', 
		'menu_name' => 'main-menu',
		'page callback' => 'contact_func', 
		'access arguments' => array('access content'), 
		'type' => MENU_SUGGESTED_ITEM,
	);
	
	return $items; 
 }
 
 
 function contact_func($title = ''){
	 
	 global $base_url;
	 $html = '';
	 
	 //$html .= '<p>Drop me a line anytime, I&rsquo;m always keen to chat.</p>';
	 $html .= drupal_render(drupal_get_form('contact_form'));
	
	 
	 return $html;
 }
 
 
 /**
* Create the newsletter signup form
*/
function contact_form($form, $form_state) {
	
	global $base_url;
	
	$form['markup'] = array(
		'#markup' => '<p>Drop me a line anytime, I&rsquo;m always keen to chat.</p>',
	);
	
	$form['name'] = array(
		'#title' => 'Ok, so your name goes in this box',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#maxlength' => 30,
		'#size' => 30
	);
	//
	$form['email'] = array(
		'#title' => '...and your email address goes in this one',
		'#type' => 'textfield',
		'#required' => TRUE,
		'#maxlength' => 30,
		'#size' => 30
	);
	//
	$form['query'] = array(
		'#title' => 'then finally... tell me, what&rsquo;s on your mind?',
		'#type' => 'textarea',
		'#required' => TRUE
	);
	
	
	
	  
	/*
	*Submit
	*/
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => 'Submit'
	);
	
	return $form;
}

/*
* Validation handler
*/
function contact_form_validate($form, &$form_state) {
	
	$pattern = '/[^a-zA-Z\ \'\.\,]/';
	if(preg_match($pattern,$form_state['values']['name'])){
		form_set_error('title', t('Please enter a name I can understand.'));
	}
	$pattern = '/http|http:|www\.|\.[a-z]{2,3}|@/';
	if(preg_match($pattern,$form_state['values']['query'])){
		form_set_error('query', t('Please do not enter links into your message.'));
	}
	//
	if(!valid_email_address($form_state['values']['email'])) {
		form_set_error('email', t('Please enter a valid email address.'));
	}
}

/*
* Submit handler
*/
function contact_form_submit($form, $form_state) {
	global $base_url, $base_path;
	
	//Send an email
	module_load_include('php', 'matt_contact', '/PHPMailer/class.phpmailer');
	
	
	$body = '<table cellpadding="8" cellspacing="0" border="0">';
	$body .= '<tr>';
	$body .= '<th colspan="2">Someone contacted you!! Yay!</th>';
	$body .= '</tr>';
	$body .= '<tr>';
	$body .= '<td>Name:</td>';
	$body .= '<td>'.$form_state['values']['name'].'</td>';
	$body .= '</tr>';
	$body .= '<tr>';
	$body .= '<td>Email:</td>';
	$body .= '<td>'.$form_state['values']['email'].'</td>';
	$body .= '</tr>';
	$body .= '<tr>';
	$body .= '<td>Query:</td>';
	$body .= '<td>'.$form_state['values']['query'].'</td>';
	$body .= '</tr>';
	$body .= '</table>';
	
	
	
	
	$mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch
	
	try {
		
		$mail->AddAddress('matt.j.bondi@gmail.com', 'Matt bondi');
		$mail->SetFrom('info@mjbondi.com', 'MjBondi Website');
		$mail->Subject = 'Contact form submission';
		$mail->AltBody = $body;
		$mail->MsgHTML($body);
		$mail->Send();
		drupal_set_message('Thank you for your thoughts. I&rsquo;ll get back to you ASAP.');
	} catch (phpmailerException $e) {
		drupal_set_message('There was an error sending your email. Terribly sorry about that!<br/>'.$e->errorMessage());
	} catch (Exception $e) {
		drupal_set_message('There was an error sending your email. Terribly sorry about that!<br/>'.$e->getMessage());
	}
	
	
	
}



